### ISSUE TITLE
`unix` is a macro defined by default by common compilers

### ISSUE THREAD

**Issue by giordano** [madler/zipflow#1]
```console
% clang - -dM -E < /dev/null | grep -i '\<unix\>'
#define unix 1
% clang --version
clang version 14.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
% gcc - -dM -E < /dev/null | grep -i '\<unix\>'  
#define unix 1
% gcc --version  
gcc (GCC) 12.2.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
This macro breaks variables called `unix`, like https://github.com/madler/zipflow/blob/d4d73304252504bbade9aa6f34332bbb00de6664/zipflow.c#L183 https://github.com/madler/zipflow/blob/d4d73304252504bbade9aa6f34332bbb00de6664/zipflow.c#L209 which makes impossible to compile the code with default standard options.

**Comment by madler** [comment]
How rude! Per the standard, C compilers are only permitted to define macros in the underscore-capital or underscore-underscore namespace.

**Comment by giordano** [comment]
To be fair, they don't when specifying a strict ISO standard like `c18`:
```console
% gcc -std=c18 - -dM -E < /dev/null | grep unix
#define __unix 1
#define __unix__ 1
% clang -std=c18 - -dM -E < /dev/null | grep unix
#define __unix 1
#define __unix__ 1
```
:slightly_smiling_face: 

But the default standard is the GNU extension `gnu18`:
```console
% gcc -std=gnu18 - -dM -E < /dev/null | grep unix
#define __unix 1
#define __unix__ 1
#define unix 1
% clang -std=gnu18 - -dM -E < /dev/null | grep unix
#define __unix 1
#define __unix__ 1
#define unix 1
```

**Comment by madler** [comment]
Fixed. Thank you for the report.
