### ISSUE TITLE
crc32_z

### ISSUE THREAD

**Issue by kofifus** [madler/zipflow#12]
Trying to compile the code I see that almost everywhere you use `crc32` but in one place only you use `crc32_z`.

I don't have easy access to `crc32_z` can I change it to `crc32` in that place also ?

**Comment by madler** [comment]
No. That needs to be `crc32_z()` because `len` is a `size_t`.

[zlib](https://github.com/madler/zlib) provides both `crc32()` and `crc32_z()`.
