### ISSUE TITLE
Access violation

### ISSUE THREAD

**Issue by kofifus** [madler/zipflow#13]
I am getting access violation (in deflate called from zip_data) when trying to add buffers to the zip

I made this simple example (windows 11, Visual Studio 2022, zlib 1.2.13 from Apache release at Apache Lounge):

(I had to add `#define _CRT_SECURE_NO_WARNINGS` to zipflow.c to compile)

```
#include <windows.h>
#include <fileapi.h>
#include <handleapi.h>
#include <iostream>
#include <stdio.h>
#include <fcntl.h>
#include <io.h>

extern "C" {
#include "zipflow.h"
}

#define SET_BINARY_MODE(file) _setmode(_fileno(file), O_BINARY)
#define FILE_ATTRIBUTE_NORMAL               0x00000080

int main(int argc, char** argv) {
  SET_BINARY_MODE(stdout);

  /*ZIP* zip = zip_open(stdout, -1);
  for (int i = 1; i < argc; i++) {
    if (zip_entry(zip, argv[i])) break;
  }
  return zip_close(zip);
  */

  time_t now = time(NULL);
  ZIP* zip = zip_open(stdout, -1);
  for (int i = 1; i < argc; i++) {
    HANDLE hFile = CreateFileA(argv[i], GENERIC_READ, FILE_SHARE_READ, NULL, OPEN_EXISTING, 0, NULL);
    DWORD dwFileSize = GetFileSize(hFile, NULL);
    BYTE* buffer = new BYTE[dwFileSize];
    DWORD dwRead = 0;
    ReadFile(hFile, buffer, dwFileSize, &dwRead, NULL);
    CloseHandle(hFile);
    if (dwRead != dwFileSize) continue;

    zip_meta(zip, argv[i], 10, FILE_ATTRIBUTE_NORMAL, now, now, now);
    int res = zip_data(zip, buffer, dwFileSize, 1);

    delete[] buffer;
  }

  return zip_close(zip);
}
```

Note that the remarked code using `zip_entry` works fine

Any idea ?

**Comment by kofifus** [comment]
The problem in  `zip_data` seems to be here:
```
        if (zip->strm.avail_in == 0) {
            zip->strm.avail_in = len > UINT_MAX ? UINT_MAX : (unsigned)len;
            len -= zip->strm.avail_in;
        }
```

I believe there are two issues:

First the code try to compress the _entire_ buffer (or `UINT_MAX`) by setting `avail_in` like that into the output buffer which is just `CHUNK` bytes big so this easily fails if the buffer is very big and doesn't compress well. `deflate` then fails with `Z_STREAM_END` but this error is ignored. From here things seem to go bad in ways I don't fully understand.

Secondly `zip->strm.avail_in` is not set to zero in the beginning which is essential for entering this `if`. In fact I fail to understand why this `if` is needed at all.

I solved this by changing the code above to

```
       //if (zip->strm.avail_in == 0) {
        zip->strm.avail_in = len > CHUNK ? CHUNK : (unsigned)len;
        len -= zip->strm.avail_in;
      //}
```

This seems to solve the issues and compression now works well.

I can submit a PR if desired.

**Comment by madler** [comment]
Thank you for the report. Fixed in https://github.com/madler/zipflow/commit/9a9320b4cf326a25677fda5878e6d19c3bb54281 .

The issue was simply not setting `avail_in` to zero at the start.

Your fix represents a different bug, i.e. overwriting `avail_in` when it is not zero. You seem to be miscontruing how `deflate()` works. The output buffer does not have to be large enough for the input. It simply returns with `Z_OK` when the output buffer is full. If not all the input was used, `avail_in` is not zero. (Hence the issue with your fix.) `Z_STREAM_END` cannot represent failure. It represents success.
