### ISSUE TITLE
conversion warnings compiling in VS2022

### ISSUE THREAD

**Issue by kofifus** [madler/zipflow#14]
Compiling 64bit / Release / VS2022 I get the following warnings:
    `if (zip->strm.avail_in == 0 && !eof) {`
>C:\src\WamiPACS 3.x\SharedClasses\zipflow.c(258,28): warning C4267: '=': conversion from 'size_t' to 'uInt', possible loss of data

  `memcpy(head->name, zip->path, zip->plen + 1);`
>C:\src\WamiPACS 3.x\SharedClasses\zipflow.c(343,19): warning C4267: '=': conversion from 'size_t' to 'uint16_t', possible loss of data

  `head->nlen = len;`
>C:\src\WamiPACS 3.x\SharedClasses\zipflow.c(745,16): warning C4267: '=': conversion from 'size_t' to 'uint16_t', possible loss of data

**Comment by madler** [comment]
You got the wrong lines of code for the first two of those. In any case, there is no loss of data in those cases (when looking at the correct lines of code). `CHUNK` is assured to fit in an `unsigned`, and `zip->plen` and `len` are assured to be less than or equal to 65535 by virtue of preceding checks.

**Comment by kofifus** [comment]
Ah yes the lines may be wrong because I had to add `#define _CRT_SECURE_NO_WARNINGS` at the beginning to prevent other warnings.
Does that mean I/you can add casts to removed these warnings ?

**Comment by madler** [comment]
I have already added the casts and the define in my local version. Those will show up in future commit here.
