### ISSUE TITLE
`d_namlen` is not always available as field of `dirent`

### ISSUE THREAD

**Issue by giordano** [madler/zipflow#2]
https://www.gnu.org/software/libc/manual/html_node/Directory-Entries.html

>` unsigned char d_namlen`
> 
>    This is the length of the file name, not including the terminating null character. Its type is `unsigned char` because that is the integer type of the appropriate size. This member ***is a BSD extension***. The symbol `_DIRENT_HAVE_D_NAMLEN` is defined if this member is available.

Emphasis in the quote is mine.  This breaks https://github.com/madler/zipflow/blob/d4d73304252504bbade9aa6f34332bbb00de6664/zipflow.c#L404-L406 on non-BSD platforms.

**Comment by madler** [comment]
Fixed. Thank you for the report.
